%% Convert MATLAB Neural Network Model to Python Format
% Description: Exports trained model weights and parameters for use in Python/NumPy

clear all; close all; clc;

fprintf('===== Converting Model to Python Format =====\n\n');

%% ===== LOAD TRAINED MODEL =====
load('model_weights.mat');

fprintf('✓ Model weights loaded\n\n');

%% ===== CREATE PYTHON-COMPATIBLE JSON FILE =====
% Create structure for JSON export
python_model = struct();

% Network architecture
python_model.architecture = struct();
python_model.architecture.input_size = 3;
python_model.architecture.hidden1_size = size(weights_biases.W1, 1);
python_model.architecture.hidden2_size = size(weights_biases.W2, 1);
python_model.architecture.output_size = 3;

% Weights and biases (convert to lists for JSON)
python_model.weights = struct();
python_model.weights.W1 = weights_biases.W1;
python_model.weights.b1 = reshape(weights_biases.b1, [], 1);
python_model.weights.W2 = weights_biases.W2;
python_model.weights.b2 = reshape(weights_biases.b2, [], 1);
python_model.weights.W3 = weights_biases.W3;
python_model.weights.b3 = reshape(weights_biases.b3, [], 1);

% Normalization parameters
python_model.normalization = struct();
python_model.normalization.input_min = reshape(weights_biases.input_min, [], 1);
python_model.normalization.input_max = reshape(weights_biases.input_max, [], 1);
python_model.normalization.output_min = reshape(weights_biases.output_min, [], 1);
python_model.normalization.output_max = reshape(weights_biases.output_max, [], 1);

% Save as JSON
json_str = jsonencode(python_model);
fid = fopen('model_for_python.json', 'w');
fprintf(fid, '%s', json_str);
fclose(fid);

fprintf('✓ Model exported to JSON: model_for_python.json\n');

%% ===== ALSO SAVE AS SIMPLE TEXT FORMAT =====
% Save weights as CSV for easy loading in Python
csvwrite('W1.csv', weights_biases.W1);
csvwrite('b1.csv', weights_biases.b1);
csvwrite('W2.csv', weights_biases.W2);
csvwrite('b2.csv', weights_biases.b2);
csvwrite('W3.csv', weights_biases.W3);
csvwrite('b3.csv', weights_biases.b3);
csvwrite('input_min.csv', weights_biases.input_min);
csvwrite('input_max.csv', weights_biases.input_max);
csvwrite('output_min.csv', weights_biases.output_min);
csvwrite('output_max.csv', weights_biases.output_max);

fprintf('✓ Individual weight matrices saved as CSV files\n');

%% ===== CREATE PYTHON INFERENCE SCRIPT =====
python_code = ['import numpy as np' newline ...
'import json' newline ...
newline ...
'class LegIKModel:' newline ...
'    """Simple feedforward neural network for inverse kinematics"""' newline ...
'    ' newline ...
'    def __init__(self, model_path="model_for_python.json"):' newline ...
'        """Load model from JSON file"""' newline ...
'        with open(model_path, ''r'') as f:' newline ...
'            model_data = json.load(f)' newline ...
'        ' newline ...
'        # Load weights' newline ...
'        self.W1 = np.array(model_data[''weights''][''W1''])' newline ...
'        self.b1 = np.array(model_data[''weights''][''b1'']).reshape(-1, 1)' newline ...
'        self.W2 = np.array(model_data[''weights''][''W2''])' newline ...
'        self.b2 = np.array(model_data[''weights''][''b2'']).reshape(-1, 1)' newline ...
'        self.W3 = np.array(model_data[''weights''][''W3''])' newline ...
'        self.b3 = np.array(model_data[''weights''][''b3'']).reshape(-1, 1)' newline ...
'        ' newline ...
'        # Load normalization parameters' newline ...
'        self.input_min = np.array(model_data[''normalization''][''input_min'']).reshape(-1, 1)' newline ...
'        self.input_max = np.array(model_data[''normalization''][''input_max'']).reshape(-1, 1)' newline ...
'        self.output_min = np.array(model_data[''normalization''][''output_min'']).reshape(-1, 1)' newline ...
'        self.output_max = np.array(model_data[''normalization''][''output_max'']).reshape(-1, 1)' newline ...
'        ' newline ...
'        print("✓ Model loaded successfully")' newline ...
'    ' newline ...
'    def normalize_input(self, x):' newline ...
'        """Normalize input to [-1, 1] range"""' newline ...
'        return 2 * (x - self.input_min) / (self.input_max - self.input_min) - 1' newline ...
'    ' newline ...
'    def denormalize_output(self, y):' newline ...
'        """Denormalize output from [-1, 1] range"""' newline ...
'        return (y + 1) / 2 * (self.output_max - self.output_min) + self.output_min' newline ...
'    ' newline ...
'    def tanh(self, x):' newline ...
'        """Hyperbolic tangent activation"""' newline ...
'        return np.tanh(x)' newline ...
'    ' newline ...
'    def predict(self, x, y, z):' newline ...
'        """' newline ...
'        Predict joint angles from foot position' newline ...
'        ' newline ...
'        Args:' newline ...
'            x, y, z: Foot position in mm' newline ...
'        ' newline ...
'        Returns:' newline ...
'            theta1, theta2, theta3: Joint angles in degrees' newline ...
'        """' newline ...
'        # Prepare input' newline ...
'        input_vec = np.array([[x], [y], [z]])' newline ...
'        ' newline ...
'        # Normalize' newline ...
'        input_norm = self.normalize_input(input_vec)' newline ...
'        ' newline ...
'        # Forward pass' newline ...
'        hidden1 = self.tanh(np.dot(self.W1, input_norm) + self.b1)' newline ...
'        hidden2 = self.tanh(np.dot(self.W2, hidden1) + self.b2)' newline ...
'        output_norm = np.dot(self.W3, hidden2) + self.b3' newline ...
'        ' newline ...
'        # Denormalize' newline ...
'        output = self.denormalize_output(output_norm)' newline ...
'        ' newline ...
'        theta1, theta2, theta3 = output.flatten()' newline ...
'        return theta1, theta2, theta3' newline ...
newline ...
'# Example usage' newline ...
'if __name__ == "__main__":' newline ...
'    # Load model' newline ...
'    model = LegIKModel("model_for_python.json")' newline ...
'    ' newline ...
'    # Test prediction' newline ...
'    x, y, z = 100, 50, -150  # Target foot position in mm' newline ...
'    theta1, theta2, theta3 = model.predict(x, y, z)' newline ...
'    ' newline ...
'    print(f"\\nTarget position: ({x:.1f}, {y:.1f}, {z:.1f}) mm")' newline ...
'    print(f"Predicted angles: θ1={theta1:.2f}°, θ2={theta2:.2f}°, θ3={theta3:.2f}°")' newline];

% Write Python script
fid = fopen('leg_ik_inference.py', 'w');
fprintf(fid, '%s', python_code);
fclose(fid);

fprintf('✓ Python inference script created: leg_ik_inference.py\n');

fprintf('\n========================================\n');
fprintf('EXPORT COMPLETE!\n\n');
fprintf('Files created:\n');
fprintf('  1. model_for_python.json - Complete model in JSON format\n');
fprintf('  2. W1.csv, b1.csv, etc. - Individual weight matrices\n');
fprintf('  3. leg_ik_inference.py - Python inference code\n\n');
fprintf('To use in Python:\n');
fprintf('  1. Copy all files to your Raspberry Pi\n');
fprintf('  2. Run: python3 leg_ik_inference.py\n');
fprintf('========================================\n');
